= cti-documentation

This is a multilingual repository to host all of the documentation for the LabVIEW Community Training Initiative.

== Building and publishing the site

The site is built and published automatically as soon as a push on the repository is done.
See the `Actions` tab for details.

== Documentation Versioning and Branching Workflow

Versioning of the documentation relies on branches.
Each version of the documentation stands in branches called `vx.y`.

NOTE: There's no need to merge those `vx.y` in main. The build and publish action is triggered on any `vx.y` branch push.

== Creating a New Version

. Create a new `vx.y` branch starting from the most recent branch version.
. Update the `version:` attribute of each `cti-doc_xx/content/antora.yml` and `cti-doc_xx/home/antora.yml` files according to the version name.

TIP: You can add a `prerelease:` attribute to suffix the version name as long as the content is not ready for an official release. The version will be accessible on the website, but it will not be displayed as the default version to the visitor.

== Building the site locally

Execute the following steps:

. Building the web site UI:
* Open a terminal in the `user-interface` folder.
* Execute the following command `npx gulp bundle`
. Build the website.
* Open a Terminal in the `antora` folder.
* execute the following command `npx antora --ui-bundle-url ../user-interface/build/ui-bundle.zip --url _<absolute path to your local repository>_ --to-dir build/sites/en  antora-playbook-en.yml`.

Once built, the website is available in the `/antora/build/sites/en` folder.

[IMPORTANT]
====
To build the web site locally, make sure following the prerequisites listed below:

* https://docs.antora.org/antora/latest/install-and-run-quickstart/[Antora install]
* https://docs.antora.org/antora-ui-default/prerequisites/[UI building prerequisites]
* https://www.npmjs.com/package/@antora/lunr-extension[Lunr extension installation]
====

== Contribute to the documentation

Please follow the instructions available https://labviewcommunitytraining.github.io/cti-documentation/en/cti-doc/contributing.html#contributing-to-the-documentation[here] to contribute to the documentation.